/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        canvas: "var(--canvas)",
        "surface-soft": "var(--surface-soft)",
        "surface-card": "var(--surface-card)",
        "surface-elevated": "var(--surface-elevated)",
        "carbon-gray": "var(--carbon-gray)",
        hairline: "var(--hairline)",
        "hairline-strong": "var(--hairline-strong)",
        "on-dark": "var(--on-dark)",
        body: "var(--body)",
        "body-strong": "var(--body-strong)",
        muted: "var(--muted)",
        "m-blue-light": "#0066b1",
        "m-blue-dark": "#1c69d4",
        "m-red": "#e22718",
        "bmw-blue": "#1c69d4",
        "electric-blue": "#0653b6",
        warning: "#f4b400",
        success: "#0fa336",
      },
      fontFamily: {
        display: [
          "Inter",
          "BMW Type Next Latin",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        sans: [
          "Inter",
          "BMW Type Next Latin",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
      },
      fontSize: {
        "display-xl": ["80px", { lineHeight: "1.0", letterSpacing: "-0.01em" }],
        "display-lg": ["56px", { lineHeight: "1.05", letterSpacing: "-0.005em" }],
        "display-md": ["40px", { lineHeight: "1.1" }],
        "display-sm": ["32px", { lineHeight: "1.15" }],
        "title-lg": ["24px", { lineHeight: "1.3" }],
        "title-md": ["20px", { lineHeight: "1.4" }],
        "title-sm": ["18px", { lineHeight: "1.4" }],
        "label-uppercase": ["14px", { lineHeight: "1.3", letterSpacing: "0.107em" }],
        "body-md": ["16px", { lineHeight: "1.5" }],
        "body-sm": ["14px", { lineHeight: "1.5" }],
        caption: ["12px", { lineHeight: "1.4", letterSpacing: "0.04em" }],
        button: ["14px", { lineHeight: "1.0", letterSpacing: "0.107em" }],
        "nav-link": ["14px", { lineHeight: "1.4", letterSpacing: "0.04em" }],
      },
      fontWeight: {
        display: 700,
        body: 300,
        regular: 400,
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        xxl: "64px",
        section: "96px",
      },
      borderRadius: {
        none: "0px",
        xs: "2px",
        sm: "4px",
        md: "6px",
        lg: "12px",
        xl: "20px",
        "2xl": "28px",
        full: "9999px",
      },
      backdropBlur: {
        glass: "24px",
        "glass-lg": "40px",
      },
      animation: {
        "fade-in": "fadeIn 220ms ease-out",
        "scale-in": "scaleIn 220ms cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-up": "slideUp 280ms cubic-bezier(0.16, 1, 0.3, 1)",
        "shimmer": "shimmer 8s linear infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
      },
    },
  },
  plugins: [],
};
